title: Tale of Two Cities
author: Charles Dickens
description: Set in London and Paris prior to and during the French Revolution, this 45-chapter novel by Charles Dickens was first published as a set of 31 weekly issues in the periodical "All the Year Round" from April through November, 1859.
repository: dagilleland/two-cities
encoding: bom|utf-8
highlighter: rouge
gem:
  github-pages
sortorderkey: order
collections:
  book1:
    title: Recalled to Life
    output: true
    order: 1
  book2:
    title: The Golden Thread
    output: true
    order: 2
  book3:
    title: The Track of a Storm
    output: true
    order: 3
